# Битрикс для проверки использует подключение к самому себе внутри контейнера. Разрешим ему это.
# TODO пока SSL тесты не любят, хоть сайт и работает по https.
<VirtualHost *:40443>
    ServerName localhost
    DocumentRoot /var/www

    SSLEngine on
    SSLCertificateFile /etc/apache2/ssl/apache.crt
    SSLCertificateKeyFile /etc/apache2/ssl/apache.key

    RewriteEngine On
    RewriteRule ^/upload/(.*)$ https://cdn.orteka.ru/upload/$1 [R=302,L,NE]

    <Directory /var/www>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /var/log/apache_ssl_error.log
    CustomLog /var/log/apache_ssl_access.log combined
</VirtualHost>
