# Битрикс для проверки использует подключение к самому себе внутри контейнера. Разрешим ему это.
<VirtualHost *:40080>
    ServerAdmin webmaster@localhost
    ServerName localhost
    DocumentRoot /var/www/html

    RewriteEngine On
    RewriteRule ^/upload/(.*)$ https://cdn.orteka.ru/upload/$1 [R=302,L,NE]

    <Directory /var/www/html>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    DirectoryIndex index.php index.html

    ErrorLog /var/log/php/apache_error.log
    CustomLog /var/log/php/apache_access.log combined
</VirtualHost>
